dist: xenial
language: java
sudo: false
jdk: openjdk11
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token:
      secure: $SONAR_TOKEN

script:
  - mvn clean package sonar:sonar -P sonar
cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw